import { MigrateUpArgs, MigrateDownArgs, sql } from "@payloadcms/db-sqlite";

// Initial schema for the portfolio CMS (tables and indexes). Safe to run on an empty database.
const statements = [
  "CREATE TABLE IF NOT EXISTS `payload_migrations` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text,\n\t`batch` numeric,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE INDEX IF NOT EXISTS `payload_migrations_updated_at_idx` ON `payload_migrations` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_migrations_created_at_idx` ON `payload_migrations` (`created_at`)",
  "CREATE TABLE IF NOT EXISTS `_faqs_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_question` text NOT NULL,\n\t`version_answer` text NOT NULL,\n\t`version_order` numeric DEFAULT 10,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`parent_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE IF NOT EXISTS `_projects_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_name` text NOT NULL,\n\t`version_type` text NOT NULL,\n\t`version_stack` text,\n\t`version_order` numeric DEFAULT 10,\n\t`version_published` integer DEFAULT true,\n\t`version_visual` text DEFAULT 'image',\n\t`version_image_id` integer,\n\t`version_image_label` text,\n\t`version_bg` text DEFAULT '#121212',\n\t`version_problem` text NOT NULL,\n\t`version_role` text NOT NULL,\n\t`version_result` text NOT NULL,\n\t`version_link` text NOT NULL,\n\t`version_link_text` text NOT NULL,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`parent_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`version_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE IF NOT EXISTS `_services_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_title` text NOT NULL,\n\t`version_description` text NOT NULL,\n\t`version_best` text,\n\t`version_icon` text DEFAULT 'site',\n\t`version_order` numeric DEFAULT 10,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`parent_id`) REFERENCES `services`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE IF NOT EXISTS `_site_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`version_seeded` integer DEFAULT false,\n\t`version_brand_name` text,\n\t`version_role` text,\n\t`version_available` text,\n\t`version_headline_pre` text,\n\t`version_headline_accent` text,\n\t`version_subline` text,\n\t`version_founder_line` text,\n\t`version_primary_cta` text,\n\t`version_secondary_cta` text,\n\t`version_photo_id` integer,\n\t`version_profile_cta` text,\n\t`version_about_headline` text,\n\t`version_process_heading` text,\n\t`version_process_note` text,\n\t`version_cta_heading` text,\n\t`version_book_heading` text,\n\t`version_book_subtext` text,\n\t`version_footer_tagline` text,\n\t`version_phone` text NOT NULL,\n\t`version_phone_label` text,\n\t`version_email` text,\n\t`version_github` text,\n\t`version_float_message` text,\n\t`version_cta_message` text,\n\t`version_seo_title` text,\n\t`version_seo_description` text,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`version_photo_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE IF NOT EXISTS `_site_v_version_about_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`text` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_site_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `_site_v_version_about_tags` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`tag` text NOT NULL,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_site_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `_site_v_version_facts` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`label` text NOT NULL,\n\t`value` text NOT NULL,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_site_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `_site_v_version_marquee` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_site_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `_site_v_version_process_steps` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_site_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `_site_v_version_stats` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL,\n\t`label` text NOT NULL,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_site_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `_site_v_version_trust` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`point` text NOT NULL,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_site_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `_skill_groups_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_title` text NOT NULL,\n\t`version_description` text,\n\t`version_icon` text DEFAULT 'server',\n\t`version_order` numeric DEFAULT 10,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`parent_id`) REFERENCES `skill_groups`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE IF NOT EXISTS `_skill_groups_v_version_items` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_skill_groups_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `faqs` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`question` text NOT NULL,\n\t`answer` text NOT NULL,\n\t`order` numeric DEFAULT 10,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS `media` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`alt` text NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`url` text,\n\t`thumbnail_u_r_l` text,\n\t`filename` text,\n\t`mime_type` text,\n\t`filesize` numeric,\n\t`width` numeric,\n\t`height` numeric,\n\t`focal_x` numeric,\n\t`focal_y` numeric\n, `sizes_thumbnail_url` text, `sizes_thumbnail_width` numeric, `sizes_thumbnail_height` numeric, `sizes_thumbnail_mime_type` text, `sizes_thumbnail_filesize` numeric, `sizes_thumbnail_filename` text)",
  "CREATE TABLE IF NOT EXISTS `payload_kv` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`key` text NOT NULL,\n\t`data` text NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS `payload_locked_documents` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`global_slug` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS `payload_locked_documents_rels` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` integer,\n\t`parent_id` integer NOT NULL,\n\t`path` text NOT NULL,\n\t`users_id` integer,\n\t`media_id` integer,\n\t`projects_id` integer,\n\t`services_id` integer,\n\t`skill_groups_id` integer,\n\t`faqs_id` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `payload_locked_documents`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`users_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`projects_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`services_id`) REFERENCES `services`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`skill_groups_id`) REFERENCES `skill_groups`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`faqs_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `payload_preferences` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`key` text,\n\t`value` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS `payload_preferences_rels` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` integer,\n\t`parent_id` integer NOT NULL,\n\t`path` text NOT NULL,\n\t`users_id` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `payload_preferences`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`users_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `projects` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`type` text NOT NULL,\n\t`stack` text,\n\t`order` numeric DEFAULT 10,\n\t`published` integer DEFAULT true,\n\t`visual` text DEFAULT 'image',\n\t`image_id` integer,\n\t`image_label` text,\n\t`bg` text DEFAULT '#121212',\n\t`problem` text NOT NULL,\n\t`role` text NOT NULL,\n\t`result` text NOT NULL,\n\t`link` text NOT NULL,\n\t`link_text` text NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE IF NOT EXISTS `services` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text NOT NULL,\n\t`best` text,\n\t`icon` text DEFAULT 'site',\n\t`order` numeric DEFAULT 10,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS \"site\" (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`seeded` integer DEFAULT false,\n\t`brand_name` text,\n\t`role` text,\n\t`available` text,\n\t`headline_pre` text,\n\t`headline_accent` text,\n\t`subline` text,\n\t`founder_line` text,\n\t`primary_cta` text,\n\t`secondary_cta` text,\n\t`photo_id` integer,\n\t`profile_cta` text,\n\t`about_headline` text,\n\t`process_heading` text,\n\t`process_note` text,\n\t`cta_heading` text,\n\t`book_heading` text,\n\t`book_subtext` text,\n\t`footer_tagline` text,\n\t`phone` text NOT NULL,\n\t`phone_label` text,\n\t`email` text,\n\t`github` text,\n\t`float_message` text,\n\t`cta_message` text,\n\t`seo_title` text,\n\t`seo_description` text,\n\t`updated_at` text,\n\t`created_at` text,\n\tFOREIGN KEY (`photo_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE IF NOT EXISTS `site_about_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `site`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `site_about_tags` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tag` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `site`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `site_facts` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`label` text NOT NULL,\n\t`value` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `site`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `site_marquee` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `site`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `site_process_steps` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `site`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `site_stats` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL,\n\t`label` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `site`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `site_trust` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`point` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `site`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `skill_groups` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text,\n\t`icon` text DEFAULT 'server',\n\t`order` numeric DEFAULT 10,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS `skill_groups_items` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `skill_groups`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE IF NOT EXISTS `users` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`email` text NOT NULL,\n\t`reset_password_token` text,\n\t`reset_password_expiration` text,\n\t`salt` text,\n\t`hash` text,\n\t`reset_password_requested_at` text,\n\t`login_attempts` numeric DEFAULT 0,\n\t`lock_until` text\n)",
  "CREATE TABLE IF NOT EXISTS `users_sessions` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` text,\n\t`expires_at` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE INDEX IF NOT EXISTS `_faqs_v_created_at_idx` ON `_faqs_v` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `_faqs_v_parent_idx` ON `_faqs_v` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_faqs_v_updated_at_idx` ON `_faqs_v` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_faqs_v_version_version_created_at_idx` ON `_faqs_v` (`version_created_at`)",
  "CREATE INDEX IF NOT EXISTS `_faqs_v_version_version_updated_at_idx` ON `_faqs_v` (`version_updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_projects_v_created_at_idx` ON `_projects_v` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `_projects_v_parent_idx` ON `_projects_v` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_projects_v_updated_at_idx` ON `_projects_v` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_projects_v_version_version_created_at_idx` ON `_projects_v` (`version_created_at`)",
  "CREATE INDEX IF NOT EXISTS `_projects_v_version_version_image_idx` ON `_projects_v` (`version_image_id`)",
  "CREATE INDEX IF NOT EXISTS `_projects_v_version_version_updated_at_idx` ON `_projects_v` (`version_updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_services_v_created_at_idx` ON `_services_v` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `_services_v_parent_idx` ON `_services_v` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_services_v_updated_at_idx` ON `_services_v` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_services_v_version_version_created_at_idx` ON `_services_v` (`version_created_at`)",
  "CREATE INDEX IF NOT EXISTS `_services_v_version_version_updated_at_idx` ON `_services_v` (`version_updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_created_at_idx` ON `_site_v` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_updated_at_idx` ON `_site_v` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_about_paragraphs_order_idx` ON `_site_v_version_about_paragraphs` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_about_paragraphs_parent_id_idx` ON `_site_v_version_about_paragraphs` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_about_tags_order_idx` ON `_site_v_version_about_tags` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_about_tags_parent_id_idx` ON `_site_v_version_about_tags` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_facts_order_idx` ON `_site_v_version_facts` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_facts_parent_id_idx` ON `_site_v_version_facts` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_marquee_order_idx` ON `_site_v_version_marquee` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_marquee_parent_id_idx` ON `_site_v_version_marquee` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_process_steps_order_idx` ON `_site_v_version_process_steps` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_process_steps_parent_id_idx` ON `_site_v_version_process_steps` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_stats_order_idx` ON `_site_v_version_stats` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_stats_parent_id_idx` ON `_site_v_version_stats` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_trust_order_idx` ON `_site_v_version_trust` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_trust_parent_id_idx` ON `_site_v_version_trust` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_site_v_version_version_photo_idx` ON `_site_v` (`version_photo_id`)",
  "CREATE INDEX IF NOT EXISTS `_skill_groups_v_created_at_idx` ON `_skill_groups_v` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `_skill_groups_v_parent_idx` ON `_skill_groups_v` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_skill_groups_v_updated_at_idx` ON `_skill_groups_v` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `_skill_groups_v_version_items_order_idx` ON `_skill_groups_v_version_items` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_skill_groups_v_version_items_parent_id_idx` ON `_skill_groups_v_version_items` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_skill_groups_v_version_version_created_at_idx` ON `_skill_groups_v` (`version_created_at`)",
  "CREATE INDEX IF NOT EXISTS `_skill_groups_v_version_version_updated_at_idx` ON `_skill_groups_v` (`version_updated_at`)",
  "CREATE INDEX IF NOT EXISTS `faqs_created_at_idx` ON `faqs` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `faqs_updated_at_idx` ON `faqs` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `media_created_at_idx` ON `media` (`created_at`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `media_filename_idx` ON `media` (`filename`)",
  "CREATE INDEX IF NOT EXISTS `media_sizes_thumbnail_sizes_thumbnail_filename_idx` ON `media` (`sizes_thumbnail_filename`)",
  "CREATE INDEX IF NOT EXISTS `media_updated_at_idx` ON `media` (`updated_at`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `payload_kv_key_idx` ON `payload_kv` (`key`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_created_at_idx` ON `payload_locked_documents` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_global_slug_idx` ON `payload_locked_documents` (`global_slug`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_faqs_id_idx` ON `payload_locked_documents_rels` (`faqs_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_media_id_idx` ON `payload_locked_documents_rels` (`media_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_order_idx` ON `payload_locked_documents_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_parent_idx` ON `payload_locked_documents_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_path_idx` ON `payload_locked_documents_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_projects_id_idx` ON `payload_locked_documents_rels` (`projects_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_services_id_idx` ON `payload_locked_documents_rels` (`services_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_skill_groups_id_idx` ON `payload_locked_documents_rels` (`skill_groups_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_users_id_idx` ON `payload_locked_documents_rels` (`users_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_locked_documents_updated_at_idx` ON `payload_locked_documents` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_created_at_idx` ON `payload_preferences` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_key_idx` ON `payload_preferences` (`key`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_order_idx` ON `payload_preferences_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_parent_idx` ON `payload_preferences_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_path_idx` ON `payload_preferences_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_rels_users_id_idx` ON `payload_preferences_rels` (`users_id`)",
  "CREATE INDEX IF NOT EXISTS `payload_preferences_updated_at_idx` ON `payload_preferences` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `projects_created_at_idx` ON `projects` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `projects_image_idx` ON `projects` (`image_id`)",
  "CREATE INDEX IF NOT EXISTS `projects_updated_at_idx` ON `projects` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `services_created_at_idx` ON `services` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `services_updated_at_idx` ON `services` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `site_about_paragraphs_order_idx` ON `site_about_paragraphs` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `site_about_paragraphs_parent_id_idx` ON `site_about_paragraphs` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `site_about_tags_order_idx` ON `site_about_tags` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `site_about_tags_parent_id_idx` ON `site_about_tags` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `site_facts_order_idx` ON `site_facts` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `site_facts_parent_id_idx` ON `site_facts` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `site_marquee_order_idx` ON `site_marquee` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `site_marquee_parent_id_idx` ON `site_marquee` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `site_photo_idx` ON `site` (`photo_id`)",
  "CREATE INDEX IF NOT EXISTS `site_process_steps_order_idx` ON `site_process_steps` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `site_process_steps_parent_id_idx` ON `site_process_steps` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `site_stats_order_idx` ON `site_stats` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `site_stats_parent_id_idx` ON `site_stats` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `site_trust_order_idx` ON `site_trust` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `site_trust_parent_id_idx` ON `site_trust` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `skill_groups_created_at_idx` ON `skill_groups` (`created_at`)",
  "CREATE INDEX IF NOT EXISTS `skill_groups_items_order_idx` ON `skill_groups_items` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `skill_groups_items_parent_id_idx` ON `skill_groups_items` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `skill_groups_updated_at_idx` ON `skill_groups` (`updated_at`)",
  "CREATE INDEX IF NOT EXISTS `users_created_at_idx` ON `users` (`created_at`)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `users_email_idx` ON `users` (`email`)",
  "CREATE INDEX IF NOT EXISTS `users_sessions_order_idx` ON `users_sessions` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `users_sessions_parent_id_idx` ON `users_sessions` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `users_updated_at_idx` ON `users` (`updated_at`)"
];

export async function up({ db }: MigrateUpArgs): Promise<void> {
  for (const statement of statements) {
    await db.run(sql.raw(statement));
  }
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export async function down(_args: MigrateDownArgs): Promise<void> {
  // Intentionally empty: the initial schema is not rolled back.
}
